background {
    monitor =
    path = ~/Wallpapers/wallpaper2.jpg
    blur_passes = 3
    blur_size = 7
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(81A1C1)
    inner_color = rgb(2E3440)
    font_color = rgb(ECEFF4)
    placeholder_text = <i>Пароль...</i>
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 128
    font_family = JetBrainsMono Nerd Font
    color = rgba(236, 239, 244, 1.0)
    position = 0, 100
    halign = center
    valign = center
}